# Two stages. The site is assembled inside the image from src/, so whatever
# Dokploy (or any Docker host) builds is guaranteed to match the source.
# Nothing has to be built by hand before pushing.

# ---- Stage 1: build the static site -------------------------------------
FROM python:3.13-alpine AS build

WORKDIR /site
COPY build.py ./
COPY src ./src

# Writes index.html, blog/**, and sitemap.xml into /site.
# build.py exits non-zero on an empty page, a missing required field, an
# unfilled placeholder, or anything other than one <h1> per page, so a broken
# page fails the image build instead of shipping.
RUN python3 build.py

# ---- Stage 2: serve -----------------------------------------------------
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Generated by stage 1
COPY --from=build /site/index.html /usr/share/nginx/html/
COPY --from=build /site/sitemap.xml /usr/share/nginx/html/
COPY --from=build /site/blog /usr/share/nginx/html/blog

# Static, not generated
COPY robots.txt /usr/share/nginx/html/
COPY assets /usr/share/nginx/html/assets

EXPOSE 80

# busybox wget ships with alpine, so no extra package is needed.
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget -q -O /dev/null http://127.0.0.1/ || exit 1
